# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIlYWUfqBSXzbqPHJjXDM6ZQ9v79s8KM
"""

import streamlit as st
import pandas as pd
import numpy as np
import json
import os
import re

# Gemini
from google import genai


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Occubuy AI Property Matching Demo",
    layout="wide"
)

st.title("🏠 Occubuy AI Property Matching Demo")
st.markdown(
    "Personalized property recommendations, buyer readiness scoring, and AI-generated explanations."
)


# ============================================================
# GEMINI CLIENT
# ============================================================

@st.cache_resource
def get_gemini_client():
    api_key = None

    # Streamlit secrets first
    try:
        if "GEMINI_API_KEY" in st.secrets:
            api_key = st.secrets["GEMINI_API_KEY"]
    except Exception:
        pass

    # Fallback to environment variable
    if not api_key:
        api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        return None

    return genai.Client(api_key=api_key)


client = get_gemini_client()


# ============================================================
# LOAD DATA
# ============================================================

@st.cache_data
def load_data():
    users_df = pd.read_csv("occubuy_users_engineered.csv")
    properties_df = pd.read_csv("occubuy_properties_demo.csv")
    return users_df, properties_df


users_df, properties_df = load_data()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def split_multiselect(value):
    if pd.isna(value):
        return []
    return [item.strip().lower() for item in str(value).split(",") if item.strip()]


def parse_budget_range(value):
    if pd.isna(value):
        return np.nan, np.nan, np.nan

    text = str(value).replace(",", "").replace(" ", "").upper()
    text = text.replace("K", "000").replace("M", "000000")
    nums = re.findall(r"\d+", text)

    if "+" in text and len(nums) >= 1:
        val = int(nums[0])
        return val, val, val

    if len(nums) >= 2:
        low = int(nums[0])
        high = int(nums[1])
        mid = (low + high) / 2
        return low, high, mid

    if len(nums) == 1:
        val = int(nums[0])
        return val, val, val

    return np.nan, np.nan, np.nan


def parse_bedrooms(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    if "studio" in text:
        return 0
    match = re.search(r"\d+", text)
    if match:
        return int(match.group())
    return np.nan


def parse_bathrooms(value):
    if pd.isna(value):
        return np.nan
    match = re.search(r"\d+", str(value))
    if match:
        return int(match.group())
    return np.nan


def yes_no_to_binary(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    if text in ["yes", "y", "true"]:
        return 1
    if text in ["no", "n", "false"]:
        return 0
    return np.nan


def timeline_to_score(value):
    if pd.isna(value):
        return 0

    text = str(value).strip().lower()

    if "immediately" in text or "soon" in text:
        return 5
    elif "1-6 months" in text or "1 to 6 months" in text or "16 months" in text:
        return 4
    elif "6-12 months" in text or "6 to 12 months" in text or "612 months" in text:
        return 3
    elif "1-2 years" in text or "1 to 2 years" in text or "12 years" in text:
        return 2
    elif "not sure" in text:
        return 1
    else:
        return 1


def make_json_safe(obj):
    if isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    elif isinstance(obj, tuple):
        return tuple(make_json_safe(v) for v in obj)
    elif isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif pd.isna(obj):
        return None
    else:
        return obj


# ============================================================
# FEATURE ENGINEERING FOR MANUAL USER INPUT
# ============================================================

def build_user_profile(
    budget_range,
    property_type,
    bedrooms,
    bathrooms,
    features,
    neighborhood,
    pre_approval,
    timeline,
    purpose,
    motivation,
    points_interest
):
    user = {
        "budget_range": budget_range,
        "property_type": ", ".join(property_type) if property_type else "",
        "bedrooms": str(bedrooms),
        "bathrooms": str(bathrooms),
        "features": ", ".join(features) if features else "",
        "neighborhood": ", ".join(neighborhood) if neighborhood else "",
        "pre_approval": pre_approval,
        "timeline": timeline,
        "purpose": purpose,
        "motivation": ", ".join(motivation) if motivation else "",
        "points_interest": points_interest
    }

    budget_min, budget_max, budget_mid = parse_budget_range(budget_range)
    user["budget_min"] = budget_min
    user["budget_max"] = budget_max
    user["budget_mid"] = budget_mid
    user["bedrooms_num"] = parse_bedrooms(str(bedrooms))
    user["bathrooms_num"] = parse_bathrooms(str(bathrooms))
    user["pre_approval_bin"] = yes_no_to_binary(pre_approval)
    user["timeline_score"] = timeline_to_score(timeline)

    # Property type flags
    for ptype in ["house", "house & land", "townhouse", "apartment"]:
        col_name = f"pref_{ptype.replace(' & ', '_').replace(' ', '_')}"
        user[col_name] = 1 if ptype in [x.lower() for x in property_type] else 0

    # Feature flags
    feature_keywords = [
        "parking",
        "pet-friendly",
        "green spaces",
        "proximity to public transport",
        "security",
        "low-maintenance options",
        "swimming pool",
        "balcony",
        "gym"
    ]

    selected_features_lower = [x.lower() for x in features]

    for feat in feature_keywords:
        col_name = "feat_" + feat.replace("-", "_").replace(" ", "_")
        user[col_name] = 1 if feat in selected_features_lower else 0

    return pd.Series(user)


# ============================================================
# MATCHING ENGINE
# ============================================================

def budget_fit_score(user, prop):
    if pd.isna(user["budget_max"]):
        return 50
    if prop["price"] <= user["budget_max"]:
        return 100
    elif prop["price"] <= user["budget_max"] * 1.10:
        return 60
    else:
        return 0


def property_type_fit_score(user, prop):
    preferred_types = split_multiselect(user["property_type"])
    if prop["property_type"].lower() in preferred_types:
        return 100
    return 0


def bedroom_bathroom_fit_score(user, prop):
    score = 0

    if not pd.isna(user["bedrooms_num"]):
        if prop["bedrooms"] == user["bedrooms_num"]:
            score += 50
        elif abs(prop["bedrooms"] - user["bedrooms_num"]) == 1:
            score += 30

    if not pd.isna(user["bathrooms_num"]):
        if prop["bathrooms"] == user["bathrooms_num"]:
            score += 50
        elif abs(prop["bathrooms"] - user["bathrooms_num"]) == 1:
            score += 30

    return score


def neighborhood_fit_score(user, prop):
    if pd.isna(user["neighborhood"]):
        return 50

    user_neighborhoods = split_multiselect(user["neighborhood"])

    if prop["neighborhood"].lower() in user_neighborhoods:
        return 100

    for pref in user_neighborhoods:
        if pref in prop["neighborhood"].lower() or prop["neighborhood"].lower() in pref:
            return 70

    return 20


def feature_fit_score(user, prop):
    score = 0
    total_requested = 0

    feature_map = {
        "feat_parking": "parking",
        "feat_pet_friendly": "pet_friendly",
        "feat_green_spaces": "green_spaces",
        "feat_proximity_to_public_transport": "public_transport",
        "feat_security": "security",
        "feat_low_maintenance_options": "low_maintenance"
    }

    for user_col, prop_col in feature_map.items():
        if user_col in user.index and user[user_col] == 1:
            total_requested += 1
            if prop[prop_col] == 1:
                score += 1

    if total_requested == 0:
        return 50

    return (score / total_requested) * 100


def calculate_match_score(user, prop):
    budget_score = budget_fit_score(user, prop)
    property_type_score = property_type_fit_score(user, prop)
    bed_bath_score = bedroom_bathroom_fit_score(user, prop)
    neighborhood_score = neighborhood_fit_score(user, prop)
    feature_score = feature_fit_score(user, prop)

    total_score = (
        0.30 * budget_score +
        0.20 * property_type_score +
        0.20 * bed_bath_score +
        0.15 * neighborhood_score +
        0.15 * feature_score
    )

    return {
        "budget_fit": round(budget_score, 1),
        "property_type_fit": round(property_type_score, 1),
        "bed_bath_fit": round(bed_bath_score, 1),
        "neighborhood_fit": round(neighborhood_score, 1),
        "feature_fit": round(feature_score, 1),
        "total_match_score": round(total_score, 1)
    }


# ============================================================
# READINESS ENGINE
# ============================================================

def calculate_readiness_score(user):
    score = 0
    reasons = []

    if user["pre_approval_bin"] == 1:
        score += 40
        reasons.append("User already has mortgage pre-approval.")
    else:
        reasons.append("User does not yet have mortgage pre-approval.")

    timeline_score = user["timeline_score"]
    score += timeline_score * 8

    if timeline_score >= 4:
        reasons.append("Purchase timeline suggests strong near-term buying intent.")
    elif timeline_score >= 2:
        reasons.append("Purchase timeline suggests moderate intent.")
    else:
        reasons.append("Purchase timeline is uncertain or longer-term.")

    purpose_text = str(user["purpose"]).lower()
    if "home to live in" in purpose_text:
        score += 15
        reasons.append("Owner-occupier intent is clear.")
    elif "both" in purpose_text or "either" in purpose_text:
        score += 10
        reasons.append("Buying purpose is somewhat flexible.")
    else:
        score += 5
        reasons.append("Pure investment intent may require a different decision path.")

    points_text = str(user["points_interest"]).strip().lower()
    if points_text == "yes":
        score += 10
        reasons.append("User is actively interested in affordability support.")
    else:
        score += 5
        reasons.append("User shows less interest in cost-reduction pathways.")

    score = min(score, 100)

    if user["pre_approval_bin"] != 1:
        main_blocker = "No mortgage pre-approval yet."
    elif timeline_score <= 1:
        main_blocker = "Unclear purchase timeline."
    else:
        main_blocker = "No major blocker identified."

    return {
        "readiness_score": score,
        "main_blocker": main_blocker,
        "readiness_reasons": reasons
    }


# ============================================================
# STRUCTURED EXPLANATION
# ============================================================

def build_structured_explanation(user, prop, score_components, readiness_output):
    reasons = []
    cautions = []

    if score_components["budget_fit"] >= 90:
        reasons.append("The property is within your preferred budget range.")
    elif score_components["budget_fit"] >= 50:
        reasons.append("The property is slightly above your preferred budget but still close.")
    else:
        cautions.append("The property is above your preferred budget range.")

    if score_components["property_type_fit"] == 100:
        reasons.append("The property type matches your stated preference.")
    else:
        cautions.append("The property type does not fully match your stated preference.")

    if score_components["bed_bath_fit"] >= 80:
        reasons.append("The bedroom and bathroom configuration strongly fits your needs.")
    elif score_components["bed_bath_fit"] >= 40:
        reasons.append("The bedroom and bathroom configuration is reasonably close to your needs.")
    else:
        cautions.append("The bedroom and bathroom configuration is not an ideal fit.")

    if score_components["neighborhood_fit"] >= 70:
        reasons.append("The neighborhood style aligns well with your preferred lifestyle.")
    elif score_components["neighborhood_fit"] >= 40:
        reasons.append("The neighborhood style is somewhat aligned with your preference.")
    else:
        cautions.append("The neighborhood style is not strongly aligned with your preference.")

    if score_components["feature_fit"] >= 70:
        reasons.append("The property includes several features you value.")
    elif score_components["feature_fit"] >= 40:
        reasons.append("The property includes some of your requested features.")
    else:
        cautions.append("The property misses several important requested features.")

    return {
        "match_reasons": reasons,
        "cautions": cautions,
        "main_blocker": readiness_output["main_blocker"],
        "readiness_reasons": readiness_output["readiness_reasons"]
    }


# ============================================================
# GEMINI EXPLANATION
# ============================================================

def generate_gemini_explanation(user, prop, score_components, readiness_output, structured_explanation):
    if client is None:
        return "Gemini API key not found. Add GEMINI_API_KEY in Streamlit secrets to enable AI explanations."

    user_safe = make_json_safe(dict(user))
    prop_safe = make_json_safe(prop)
    score_components_safe = make_json_safe(score_components)
    readiness_output_safe = make_json_safe(readiness_output)
    structured_explanation_safe = make_json_safe(structured_explanation)

    prompt = f"""
You are an AI property advisor for Occubuy.

Write a concise explanation in 2 short paragraphs:
1. Explain why the property is a match
2. Briefly explain the buyer's readiness and the next best step

BUYER PROFILE:
{json.dumps(user_safe, indent=2)}

RECOMMENDED PROPERTY:
{json.dumps(prop_safe, indent=2)}

MATCH SCORES:
{json.dumps(score_components_safe, indent=2)}

READINESS OUTPUT:
{json.dumps(readiness_output_safe, indent=2)}

STRUCTURED EXPLANATION INPUT:
{json.dumps(structured_explanation_safe, indent=2)}

Rules:
- Be specific
- Be natural and human
- Do not invent facts
- Do not mention internal scoring weights
- End with one practical next step
"""

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        return response.text
    except Exception as e:
        return f"Gemini error: {e}"


# ============================================================
# RECOMMENDATION PIPELINE
# ============================================================

def recommend_properties_for_user(user_row, properties_df, top_n=3):
    results = []
    readiness_output = calculate_readiness_score(user_row)

    for _, prop in properties_df.iterrows():
        score_components = calculate_match_score(user_row, prop)

        structured_explanation = build_structured_explanation(
            user=user_row,
            prop=prop,
            score_components=score_components,
            readiness_output=readiness_output
        )

        results.append({
            "property_id": prop["property_id"],
            "suburb": prop["suburb"],
            "price": prop["price"],
            "property_type": prop["property_type"],
            "bedrooms": prop["bedrooms"],
            "bathrooms": prop["bathrooms"],
            "neighborhood": prop["neighborhood"],
            "match_score": score_components["total_match_score"],
            "score_components": score_components,
            "property_row": prop.to_dict(),
            "readiness_output": readiness_output,
            "structured_explanation": structured_explanation
        })

    results = sorted(results, key=lambda x: x["match_score"], reverse=True)
    return results[:top_n]


# ============================================================
# SIDEBAR INPUTS
# ============================================================

st.sidebar.header("Buyer Profile")

budget_range = st.sidebar.selectbox(
    "Estimated Budget Range",
    [
        "$500K-$750K",
        "$750K-$900K",
        "$900K-$1.1M",
        "$1.1M+"
    ]
)

property_type = st.sidebar.multiselect(
    "Preferred Property Type",
    ["House", "House & Land", "Townhouse", "Apartment"],
    default=["House"]
)

bedrooms = st.sidebar.selectbox("Preferred Bedrooms", [1, 2, 3, 4, 5])
bathrooms = st.sidebar.selectbox("Preferred Bathrooms", [1, 2, 3])

features = st.sidebar.multiselect(
    "Important Features",
    [
        "Parking",
        "Pet-friendly",
        "Green spaces",
        "Proximity to public transport",
        "Security",
        "Low-maintenance options",
        "Swimming pool",
        "Balcony",
        "Gym"
    ],
    default=["Parking", "Security"]
)

neighborhood = st.sidebar.multiselect(
    "Preferred Neighborhood Type",
    [
        "Quiet & residential",
        "Family-friendly",
        "Urban & vibrant",
        "Nature-focused"
    ],
    default=["Family-friendly"]
)

pre_approval = st.sidebar.radio("Mortgage Pre-Approval", ["Yes", "No"])
timeline = st.sidebar.selectbox(
    "When do you intend to purchase?",
    [
        "Immediately / Soon",
        "1-6 months",
        "6-12 months",
        "1-2 years",
        "Not sure"
    ]
)

purpose = st.sidebar.selectbox(
    "Primary Buying Purpose",
    [
        "A home to live in",
        "Investment property",
        "Either / Both"
    ]
)

motivation = st.sidebar.multiselect(
    "Main Motivations",
    [
        "Stability & security",
        "Family needs",
        "Building wealth",
        "Retirement planning",
        "Investment opportunity"
    ],
    default=["Stability & security"]
)

points_interest = st.sidebar.radio(
    "Interested in points to reduce property cost?",
    ["Yes", "No"]
)

run_match = st.sidebar.button("Find My Matches")


# ============================================================
# MAIN APP LOGIC
# ============================================================

if run_match:
    user_profile = build_user_profile(
        budget_range=budget_range,
        property_type=property_type,
        bedrooms=bedrooms,
        bathrooms=bathrooms,
        features=features,
        neighborhood=neighborhood,
        pre_approval=pre_approval,
        timeline=timeline,
        purpose=purpose,
        motivation=motivation,
        points_interest=points_interest
    )

    top_matches = recommend_properties_for_user(user_profile, properties_df, top_n=3)
    top_match = top_matches[0]

    tab1, tab2, tab3, tab4 = st.tabs([
        "Top Matches",
        "Why It Matches",
        "Buyer Readiness",
        "Dataset View"
    ])

    # --------------------------------------------------------
    # TAB 1: TOP MATCHES
    # --------------------------------------------------------
    with tab1:
        st.subheader("Top Recommended Properties")

        for i, match in enumerate(top_matches, 1):
            with st.container():
                st.markdown(f"### Recommendation #{i}")
                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric("Suburb", match["suburb"])
                    st.metric("Property Type", match["property_type"].title())

                with col2:
                    st.metric("Price", f"${match['price']:,}")
                    st.metric("Bedrooms", match["bedrooms"])

                with col3:
                    st.metric("Bathrooms", match["bathrooms"])
                    st.metric("Match Score", f"{match['match_score']} / 100")

                st.markdown(f"**Neighborhood:** {match['neighborhood']}")
                st.divider()

    # --------------------------------------------------------
    # TAB 2: WHY IT MATCHES
    # --------------------------------------------------------
    with tab2:
        st.subheader("Why the Top Match Fits")

        st.markdown("### Structured Match Reasons")
        for reason in top_match["structured_explanation"]["match_reasons"]:
            st.success(reason)

        st.markdown("### Cautions")
        if top_match["structured_explanation"]["cautions"]:
            for caution in top_match["structured_explanation"]["cautions"]:
                st.warning(caution)
        else:
            st.info("No major concerns identified.")

        st.markdown("### Score Breakdown")
        score_df = pd.DataFrame(
            list(top_match["score_components"].items()),
            columns=["Component", "Score"]
        )
        st.dataframe(score_df, use_container_width=True)

        st.markdown("### AI Explanation")
        if st.button("Generate Gemini Explanation"):
            with st.spinner("Generating AI explanation..."):
                explanation = generate_gemini_explanation(
                    user=user_profile,
                    prop=top_match["property_row"],
                    score_components=top_match["score_components"],
                    readiness_output=top_match["readiness_output"],
                    structured_explanation=top_match["structured_explanation"]
                )
                st.write(explanation)

    # --------------------------------------------------------
    # TAB 3: BUYER READINESS
    # --------------------------------------------------------
    with tab3:
        st.subheader("Buyer Readiness")

        readiness_score = top_match["readiness_output"]["readiness_score"]
        main_blocker = top_match["readiness_output"]["main_blocker"]

        st.metric("Readiness Score", f"{readiness_score} / 100")
        st.progress(min(readiness_score / 100, 1.0))

        st.markdown("### Main Blocker")
        st.warning(main_blocker)

        st.markdown("### Readiness Insights")
        for reason in top_match["readiness_output"]["readiness_reasons"]:
            st.write(f"- {reason}")

        st.markdown("### Suggested Next Step")
        if "pre-approval" in main_blocker.lower():
            st.info("A strong next step is getting mortgage pre-approval or borrowing clarity.")
        elif "timeline" in main_blocker.lower():
            st.info("A strong next step is clarifying your purchase timeframe and narrowing your search.")
        else:
            st.info("A strong next step is reviewing top matches and shortlisting the most suitable options.")

    # --------------------------------------------------------
    # TAB 4: DATASET VIEW
    # --------------------------------------------------------
    with tab4:
        st.subheader("Demo Property Dataset")
        st.dataframe(properties_df, use_container_width=True)

else:
    st.info("Complete the buyer profile in the sidebar, then click **Find My Matches**.")